# Generated by Django 4.2.6 on 2023-12-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='/default_profile_image/blank_profile.png', upload_to='default_profile_image/'),
        ),
    ]
