# Generated by Django 5.0 on 2023-12-15 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Journique.category'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='file',
            field=models.ImageField(upload_to='pins/'),
        ),
    ]
