version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - myproject-network
    volumes:
      - ./Journique:/app
    environment:
      - PWD=/app
  db:
    volumes:
      - postgres_data:/var/lib/postgresql/data
    image: postgres:latest
    environment:
      POSTGRES_DB: "journiquedb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "23085634"
    networks:
      - myproject-network

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web

networks:
  myproject-network:
    driver: bridge

volumes:
  postgres_data:
